language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install ."
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-xdist
  - pip install tox

# command to run tests
script:
  - tox -e $TOX_ENV
